apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    name: mongo-pod
    app: demo-server-admin-pod

spec:
  containers:
    - name: mongo
      image: mongo
      ports:
        - containerPort: 27017
