apiVersion: v1
kind: Service
metadata:
  name: mongo-delivery
  labels:
    name: db-pod
    app: demo-server-admin-pod

spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
      name: mongo-pod
      app: demo-server-admin-pod
