apiVersion: v1
kind: Service
metadata:
  name: server-delivery-pod
  labels:
    name: server-delivery-pod
    app: demo-server-delivery-pod

spec:
  type: LoadBalancer
  ports:
    - port: 5003
      targetPort: 5003
  selector:
      name: server-delivery-pod
      app: demo-server-delivery-pod
